import { Metadata } from 'next';
import Head from 'next/head';
import './styles/main.scss';

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Head>
                {process.env.NEXT_PUBLIC_STAGE !== 'development' && (
                    <>
                        {/* <!-- Google tag (gtag.js) --> */}
                        <script
                            async
                            src="https://www.googletagmanager.com/gtag/js?id=G-8YTQH59D71"
                        />
                        <script
                            dangerouslySetInnerHTML={{
                                __html: `window.dataLayer = window.dataLayer || [];
                                function gtag(){dataLayer.push(arguments);}
                                gtag('js', new Date());
                              
                                gtag('config', 'G-8YTQH59D71');`,
                            }}
                        />
                    </>
                )}
            </Head>
            <body data-app-version={process.env.APP_VERSION}>{children}</body>
        </html>
    );
}
