import './styles/main.scss';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body data-app-version={process.env.APP_VERSION}>
                {children}
                <p className="version">{`Version ${process.env.APP_VERSION}`}</p>
            </body>
        </html>
    );
}
