version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - database
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    networks:
      - main
      - database
    image: adminer
    ports:
      - 8080:8080

  cache:
    image: redis:latest
    restart: always
    networks:
      - database

  traefik:
    image: traefik:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    # Traefik has to be in all networks in order to resolve properly the containers it is trying to contact
    networks:
      - main
      - database

  api:
    restart: always
    # deploy:
    #   mode: replicated
    #   replicas: 2
    build:
      context: .
      dockerfile: ./back/Dockerfile.back
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    networks:
      - main
      - database
    depends_on:
      - db
      - cache
    labels:
      - traefik.enable=true
      # https://community.traefik.io/t/solved-strange-504-gateway-timeout-behaviour/10573
      # TODO: Verify if its efficient...
      - traefik.docker.network=composite_main
      - traefik.http.services.api.loadbalancer.server.port=3002
      - traefik.http.services.api.loadBalancer.sticky.cookie.name=server_id
      - traefik.http.services.api.loadBalancer.sticky.cookie.httpOnly=true
      - traefik.http.middlewares.api_middleware.headers.accessControlAllowCredentials=true
      - traefik.http.middlewares.api_middleware.headers.accessControlAllowHeaders=Content-Type,Authorization,baggage,sentry-trace
      - traefik.http.middlewares.api_middleware.headers.accessControlAllowMethods=GET,POST,DELETE,PATCH
      - traefik.http.routers.api.rule=Host(`api.localhost`)
      - traefik.http.middlewares.api_middleware.headers.accesscontrolalloworiginlist=http://front.localhost
      - traefik.http.routers.api.middlewares=api_middleware

  front:
    restart: always
    build:
      context: .
      dockerfile: ./front/Dockerfile.front
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    env_file:
      - ./front/.env
    networks:
      - main
    labels:
      - traefik.enable=true
      - traefik.docker.network=main
      - traefik.http.services.front.loadbalancer.server.port=3000
      - traefik.http.routers.front.rule=Host(`front.localhost`)

networks:
  main:
    name: composite_main
  database:
    name: composite_database
# Note to myself in order to stop losing precious life time:
# With the directive "traefik.docker.network=", I should not reference the network alias,
# like it is done to associate service and network with the docker-compose spec.
# I should reference the network name, the one that is printed when you do "docker network ls"
