FROM node:18-alpine AS runner

RUN apk add --update --no-cache openssl1.1-compat

WORKDIR /app
COPY . .

RUN npm i -w packages -w back
RUN npm run build -w packages
RUN cd back && npx prisma generate

ENTRYPOINT ["npm", "run", "start:dev", "-w", "back"]