FROM node:18-alpine AS base
WORKDIR /app
COPY . .

RUN apk add --update --no-cache \
    make \
    g++ \
    py3-pip \
    libc6-compat && \
    npm i && \
    npm run build -w packages && \
    npm cache clean --force && \
    rm -rf /var/cache/apk/*