*
!.npmrc

!front
front/node_modules
front/.next

!core_api
core_api/node_modules
core_api/dist

!real_time_api
real_time_api/node_modules
real_time_api/dist

!packages
packages/core/node_modules
packages/core-api-client/node_modules

!./package.json