import { Metadata } from 'next';
import Script from 'next/script';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import '../styles/main.scss';
import { WithMainApp } from '../WithMainApp';
import { i18n, type Locale } from '../../i18n-config';

export async function generateStaticParams() {
    return i18n.locales.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
    params: { lng },
}: {
    children: React.ReactNode;
    params: { lng: Locale };
}) {
    return (
        <html lang={lng}>
            {process.env.NEXT_PUBLIC_STAGE !== 'development' && (
                <>
                    {/* <!-- Google tag (gtag.js) --> */}
                    <Script
                        async
                        src="https://www.googletagmanager.com/gtag/js?id=G-8YTQH59D71"
                        strategy="lazyOnload"
                    />
                    <Script
                        id="google-analytics"
                        dangerouslySetInnerHTML={{
                            __html: `window.dataLayer = window.dataLayer || [];
                                function gtag(){dataLayer.push(arguments);}
                                gtag('js', new Date());
                              
                                gtag('config', 'G-8YTQH59D71');`,
                        }}
                    />
                </>
            )}
            <body data-app-version={process.env.APP_VERSION}>
                <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                    <WithMainApp>{children}</WithMainApp>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
