/* tslint:disable */
/* eslint-disable */
/**
 * Composite API
 * Composite the game API
 *
 * The version of the OpenAPI document: 1.0.0-next.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGameDto
 */
export interface UpdateGameDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateGameDto
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateGameDto
     */
    status: UpdateGameDtoStatusEnum;
}


/**
 * @export
 */
export const UpdateGameDtoStatusEnum = {
    Started: 'STARTED',
    Finished: 'FINISHED'
} as const;
export type UpdateGameDtoStatusEnum = typeof UpdateGameDtoStatusEnum[keyof typeof UpdateGameDtoStatusEnum];


/**
 * Check if a given object implements the UpdateGameDto interface.
 */
export function instanceOfUpdateGameDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "duration" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function UpdateGameDtoFromJSON(json: any): UpdateGameDto {
    return UpdateGameDtoFromJSONTyped(json, false);
}

export function UpdateGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGameDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'status': json['status'],
    };
}

export function UpdateGameDtoToJSON(value?: UpdateGameDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'duration': value.duration,
        'status': value.status,
    };
}

