/* tslint:disable */
/* eslint-disable */
/**
 * Composite API
 * Composite the game API
 *
 * The version of the OpenAPI document: 1.0.0-next.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGameResponse
 */
export interface CreateGameResponse {
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateGameResponse
     */
    additionalExposedPorts: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof CreateGameResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGameResponse
     */
    roomId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateGameResponse
     */
    processId: string;
}

/**
 * Check if a given object implements the CreateGameResponse interface.
 */
export function instanceOfCreateGameResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "additionalExposedPorts" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "roomId" in value;
    isInstance = isInstance && "processId" in value;

    return isInstance;
}

export function CreateGameResponseFromJSON(json: any): CreateGameResponse {
    return CreateGameResponseFromJSONTyped(json, false);
}

export function CreateGameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGameResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'additionalExposedPorts': json['additionalExposedPorts'],
        'status': json['status'],
        'roomId': json['roomId'],
        'processId': json['processId'],
    };
}

export function CreateGameResponseToJSON(value?: CreateGameResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'additionalExposedPorts': value.additionalExposedPorts,
        'status': value.status,
        'roomId': value.roomId,
        'processId': value.processId,
    };
}

