/* tslint:disable */
/* eslint-disable */
/**
 * Composite API
 * Composite the game API
 *
 * The version of the OpenAPI document: 1.0.0-next.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSoloGameDto
 */
export interface CreateSoloGameDto {
    /**
     * 
     * @type {string}
     * @memberof CreateSoloGameDto
     */
    region: string;
}

/**
 * Check if a given object implements the CreateSoloGameDto interface.
 */
export function instanceOfCreateSoloGameDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "region" in value;

    return isInstance;
}

export function CreateSoloGameDtoFromJSON(json: any): CreateSoloGameDto {
    return CreateSoloGameDtoFromJSONTyped(json, false);
}

export function CreateSoloGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSoloGameDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'region': json['region'],
    };
}

export function CreateSoloGameDtoToJSON(value?: CreateSoloGameDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'region': value.region,
    };
}

