/* tslint:disable */
/* eslint-disable */
/**
 * Composite API
 * Composite the game API
 *
 * The version of the OpenAPI document: 1.0.0-next.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinishGameDto
 */
export interface FinishGameDto {
    /**
     * 
     * @type {number}
     * @memberof FinishGameDto
     */
    endTime: number;
}

/**
 * Check if a given object implements the FinishGameDto interface.
 */
export function instanceOfFinishGameDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "endTime" in value;

    return isInstance;
}

export function FinishGameDtoFromJSON(json: any): FinishGameDto {
    return FinishGameDtoFromJSONTyped(json, false);
}

export function FinishGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinishGameDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endTime': json['endTime'],
    };
}

export function FinishGameDtoToJSON(value?: FinishGameDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'endTime': value.endTime,
    };
}

