import { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import '../../styles/main.scss';
import { WithMainApp } from '../../WithMainApp';
import { i18n, type Locale } from '../../../i18n-config';

export async function generateStaticParams() {
    return i18n.locales.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
    params: { lng },
}: {
    children: React.ReactNode;
    params: { lng: Locale };
}) {
    return (
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <WithMainApp lng={lng}>{children}</WithMainApp>
        </AppRouterCacheProvider>
    );
}
